### ISSUE TITLE
Back transition not works correct

### ISSUE THREAD

**Issue by xamarinium** [jsuarezruiz/xamarin-forms-page-transitions#1]
Hi, first of all thank you for your tutorial and example!!!

So, I found a little issue, when you go back to first page (back transition) second page hides (screen is white) and transition is not between second and first page, but from "white" page and first page.

p.s. to test it you can set background to your pages and you will see it.

Thx again for your tutorial.

**Comment by matthieucolle** [comment]
Hi ! 
I have exalty the same problem. 
Thanks for all.

**Comment by jsuarezruiz** [comment]
Tested and you are right. Need to review and do some changes to fix this.

**Comment by vhugogarcia** [comment]
Excuse me friends, Is there a public nuget package to install it?

**Comment by jsuarezruiz** [comment]
No, not in these moments, do you see it interesting (after reviewing bugs)?

**Comment by IgorStrekha** [comment]
I have the same problem. But I have some opinion why. I think that we are doing Pop,  second page is destroying and we see blank screen (100-200 ms), after that working animation finally we see First page in the our  stack. Please correct me.

**Comment by rudyspano** [comment]
Same problem. Does someone find a workaround for this issue?

**Comment by JFMG** [comment]
Should be fixed in my PR:
https://github.com/jsuarezruiz/xamarin-forms-page-transitions/pull/3

**Comment by IgorStrekha** [comment]
@JFMG  hello. I've implemented your code. Please look at the video. I think we have the same issue.  (https://www.screencast.com/t/ioL2emvhsA)

**Comment by JFMG** [comment]
You are right. The override method OnPopViewAsync is called before the override method RemoveView is called. That is causing the problem in my pull request. I will need to take another look into that

**Comment by JFMG** [comment]
I've made some changes in my code. I am not sure, if I got the correct behavior now. Can you please check? http://www.screencast.com/t/6ikbyXkumW

**Comment by jsuarezruiz** [comment]
Looks nice @JFMG

**Comment by rudyspano** [comment]
Hi, Thank you.with the last version, if we set the background color of the root Grid of the DetailPage to red and slow down animations of enter_left, enter_right, exit_left end exit_right, we clearly see that on Back the content of the page is cleared before the animation using SlideFromRight or SlideFromLeft scenarios.
In my option, that's a Xamarin Forms bug/behavior/optimization on Pop.

**Comment by JFMG** [comment]
@jsuarezruiz Please have a look at my new pull request. I've upgraded the project to NET standard 2.0 and included my previous fixes and enhancements. The back transition works now in Android too. However, I don't think it fixes the issue mentioned by @rudyspano where the background is cleared when the transition starts

**Comment by rudyspano** [comment]
The error I've mentionned (Background Cleared on Back) is now Fixed with the Xamarin Forms 3 Update!

**Comment by JFMG** [comment]
Maybe we should then update the Xamarin Forms version in this project :-)

**Comment by jsuarezruiz** [comment]
I will do!

**Comment by jsuarezruiz** [comment]
Updated to Xamarin.Forms 3.0 :)
