### ISSUE TITLE
How can I integrate these transitions on Xamarin.Forms with PRISM library?

### ISSUE THREAD

**Issue by vhugogarcia** [jsuarezruiz/xamarin-forms-page-transitions#2]
Hello @jsuarezruiz 

I would like to thank you for this amazing share you did for transitions. I'm wondering if you know how to integrate it with PRISM v6.x or 7.x

Any idea?

Thanks in advance

**Comment by vhugogarcia** [comment]
Hello @idimkk ,

I ended discarding this. It was not required anymore. so, I did not have to implement it. I'm sorry :(

**Comment by RadwanIbrahim** [comment]
@jsuarezruiz thank you very much for your great effort @vhugogarcia  and @idimkk  I was looking for doing this too so I developed a small sample for demonstrating this. here it is https://github.com/RadwanIbrahim/XF-TranstionPage-with-Prism

**Comment by jsuarezruiz** [comment]
Thanks!
